//DO NOT EDIT THIS FILE, it is generated by idlcpp
//http://www.idlcpp.org

#pragma once

#include "../pafcore/Introspectable.h"
#include "../pafcore/SmartPtr.h"
class Node;
namespace pafcore{ class ClassType; }


class Scene : public pafcore::Introspectable
{
public:
	static ::pafcore::ClassType* GetType();
	::pafcore::ClassType* getType();
	void* getAddress();

	Scene();

	static ::pafcore::UniquePtr<Scene> New();


	friend class Node;
	Scene(const Scene&) = delete;
	Scene(Scene&&) = delete;
public:
	pafcore::BorrowedPtr<Node> Scene::getRootNode() const
	{
		return pafcore::BorrowedPtr<Node>(m_rootNode);
	}
public:
	void check__();
protected:
	pafcore::UniquePtr<Node> m_rootNode;

};
